// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'apiKeys.dart'; // Imports the actual API keys (git-ignored)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// This file imports API keys from apiKeys.dart (which is git-ignored).
/// The actual keys are stored in apiKeys.dart, while apiKeys.dart.example
/// serves as a template for team members.
///
/// Example:
/// ```dart
/// import 'package:nexus/firebase_setup/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Check if running in test mode via environment variable
    const isTesting = bool.fromEnvironment('TESTING', defaultValue: false);

    if (kIsWeb) {
      return isTesting ? _webTest : _webLive;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return isTesting ? _androidTest : _androidLive;
      case TargetPlatform.iOS:
        return isTesting ? _iosTest : _iosLive;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return isTesting ? _windowsTest : _windowsLive;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Live (production) Firebase options
  static const FirebaseOptions _webLive = FirebaseOptions(
    apiKey: webLiveApiKey, // ← From apiKeys.dart
    appId: webLiveAppId, // ← From apiKeys.dart
    messagingSenderId: '994254093528',
    projectId: 'nexus-773',
    authDomain: 'nexus-773.firebaseapp.com',
    storageBucket: 'nexus-773.firebasestorage.app',
  );

  static const FirebaseOptions _androidLive = FirebaseOptions(
    apiKey: androidLiveApiKey, // ← From apiKeys.dart
    appId: androidLiveAppId, // ← From apiKeys.dart
    messagingSenderId: '994254093528',
    projectId: 'nexus-773',
    storageBucket: 'nexus-773.firebasestorage.app',
  );

  static const FirebaseOptions _iosLive = FirebaseOptions(
    apiKey: iosLiveApiKey, // ← From apiKeys.dart
    appId: iosLiveAppId, // ← From apiKeys.dart
    messagingSenderId: '994254093528',
    projectId: 'nexus-773',
    storageBucket: 'nexus-773.firebasestorage.app',
    iosBundleId: 'com.life.nexus',
  );

  static const FirebaseOptions _windowsLive = FirebaseOptions(
    apiKey: windowsLiveApiKey, // ← From apiKeys.dart
    appId: windowsLiveAppId, // ← From apiKeys.dart
    messagingSenderId: '994254093528',
    projectId: 'nexus-773',
    authDomain: 'nexus-773.firebaseapp.com',
    storageBucket: 'nexus-773.firebasestorage.app',
  );

  // Test (staging/testing) Firebase options
  static const FirebaseOptions _webTest = FirebaseOptions(
    apiKey: webTestApiKey, // ← From apiKeys.dart
    appId: webTestAppId, // ← From apiKeys.dart
    messagingSenderId: '994254093528',
    projectId: 'nexus-773',
    authDomain: 'nexus-773.firebaseapp.com',
    storageBucket: 'nexus-773.firebasestorage.app',
  );

  static const FirebaseOptions _androidTest = FirebaseOptions(
    apiKey: androidTestApiKey, // ← From apiKeys.dart
    appId: androidTestAppId, // ← From apiKeys.dart
    messagingSenderId: '994254093528',
    projectId: 'nexus-773',
    storageBucket: 'nexus-773.firebasestorage.app',
  );

  static const FirebaseOptions _iosTest = FirebaseOptions(
    apiKey: iosTestApiKey, // ← From apiKeys.dart
    appId: iosTestAppId, // ← From apiKeys.dart
    messagingSenderId: '994254093528',
    projectId: 'nexus-773',
    storageBucket: 'nexus-773.firebasestorage.app',
    iosBundleId: 'com.life.nexus',
  );

  static const FirebaseOptions _windowsTest = FirebaseOptions(
    apiKey: windowsTestApiKey, // ← From apiKeys.dart
    appId: windowsTestAppId, // ← From apiKeys.dart
    messagingSenderId: '994254093528',
    projectId: 'nexus-773',
    authDomain: 'nexus-773.firebaseapp.com',
    storageBucket: 'nexus-773.firebasestorage.app',
  );
}
