// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_bL3ZkUfuc_-7NPLb8tO9uq_rArk_lM',
    appId: '1:252181378489:web:3291bf0e91daf6f6d17268',
    messagingSenderId: '252181378489',
    projectId: 'nexus-73',
    authDomain: 'nexus-73.firebaseapp.com',
    storageBucket: 'nexus-73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoqaEsyQdFGNDZ-qwwLLcED537RKrWzS4',
    appId: '1:252181378489:android:9788f1de126744f5d17268',
    messagingSenderId: '252181378489',
    projectId: 'nexus-73',
    storageBucket: 'nexus-73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNuN67IyF82eJvO8FVlMi8jeqbLtDS8hk',
    appId: '1:252181378489:ios:1a2be8902f7032f8d17268',
    messagingSenderId: '252181378489',
    projectId: 'nexus-73',
    storageBucket: 'nexus-73.firebasestorage.app',
    iosClientId:
        '252181378489-jqfoaf5ts34dt25dv45rad5vg6v0c03v.apps.googleusercontent.com',
    iosBundleId: 'com.life.nexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY_bL3ZkUfuc_-7NPLb8tO9uq_rArk_lM',
    appId: '1:252181378489:web:671fea2b4641ff91d17268',
    messagingSenderId: '252181378489',
    projectId: 'nexus-73',
    authDomain: 'nexus-73.firebaseapp.com',
    storageBucket: 'nexus-73.firebasestorage.app',
  );
}
